version = 5.3.1
archive_dir = /etc/letsencrypt/archive/kannarimusicacademy.com
cert = /etc/letsencrypt/live/kannarimusicacademy.com/cert.pem
privkey = /etc/letsencrypt/live/kannarimusicacademy.com/privkey.pem
chain = /etc/letsencrypt/live/kannarimusicacademy.com/chain.pem
fullchain = /etc/letsencrypt/live/kannarimusicacademy.com/fullchain.pem
[renewalparams]
account = 09d8afe4d878caf5e13eb81733a809b2
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
