# Generated by Django 6.0.2 on 2026-02-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_modulelesson_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='audio_messages_used_this_month',
            field=models.IntegerField(default=0, help_text='Audio messages sent this month'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_monthly_reset',
            field=models.DateField(blank=True, help_text='Last date monthly counters were reset', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='live_sessions_used_this_month',
            field=models.IntegerField(default=0, help_text='Live sessions used this month'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_audio_messages_per_month',
            field=models.IntegerField(default=0, help_text='Max audio messages teacher can send per month (0 = none)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_live_sessions_per_month',
            field=models.IntegerField(default=0, help_text='Max live video sessions per month (0 = none)'),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the session ended', null=True),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Whether the session is currently live'),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='recording_url',
            field=models.URLField(blank=True, help_text='URL to session recording if any', null=True),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='room_name',
            field=models.CharField(blank=True, help_text='Auto-generated unique room name for Jitsi', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='session_type',
            field=models.CharField(choices=[('video_call', 'Video Call'), ('audio_call', 'Audio Call'), ('in_person', 'In Person')], default='video_call', max_length=20),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When teacher started the live session', null=True),
        ),
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio_messages/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional: associate message with a course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_messages', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_audio_messages', to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_audio_messages', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '60. Audio Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
