# Generated by Django 5.2.5 on 2026-02-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_lessonassignment_audio_and_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='can_teach_minors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('in_review', 'In Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('child_safety', 'Child Safety Policy'), ('code_of_conduct', 'Code of Conduct'), ('background_check_consent', 'Background Check Consent'), ('other', 'Other')], max_length=40)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '18a. Policy Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_verification_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('background_check_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('agreement_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teacher_verifications', to='main.admin')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '18b. Teacher Verifications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherIDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='teacher_verification/id_docs/')),
                ('document_type', models.CharField(default='government_id', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_id_verifications', to='main.admin')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to='main.teacherverification')),
            ],
            options={
                'verbose_name_plural': '18c. Teacher ID Verifications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherBackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=120, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('confirmation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='teacher_verification/background_checks/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_background_checks', to='main.admin')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_check', to='main.teacherverification')),
            ],
            options={
                'verbose_name_plural': '18d. Teacher Background Checks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAgreementSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('child_safety', 'Child Safety Policy'), ('code_of_conduct', 'Code of Conduct'), ('background_check_consent', 'Background Check Consent'), ('other', 'Other')], max_length=40)),
                ('policy_version', models.CharField(default='1.0', max_length=20)),
                ('signature_text', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('policy_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_signatures', to='main.policydocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agreement_signatures', to='main.admin')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_signatures', to='main.teacherverification')),
            ],
            options={
                'verbose_name_plural': '18e. Teacher Agreement Signatures',
                'ordering': ['-signed_at'],
            },
        ),
    ]
