# Generated by Django 5.2.5 on 2026-02-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_teacher_verification_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '6a. Parent Accounts',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_account_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='has_minor_participant',
            field=models.BooleanField(default=False, help_text='True if session student is a minor'),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='recording_enabled',
            field=models.BooleanField(default=True, help_text='Enable safety recording/logging for this session'),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='requires_parental_approval',
            field=models.BooleanField(default=False, help_text='Derived from minor participant'),
        ),
        migrations.CreateModel(
            name='SessionParticipantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_role', models.CharField(default='student', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_logs', to='main.teachersession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participant_logs', to='main.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participant_logs', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '60b. Session Participant Logs',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('authorization_mode', models.CharField(choices=[('pre_authorized', 'Pre-authorized Multiple Sessions'), ('per_session_login', 'Parental Login Each Session')], default='pre_authorized', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='main.parentaccount')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='main.student')),
            ],
            options={
                'verbose_name_plural': '6b. Student Parent Links',
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('session', 'Session'), ('audio_message', 'Audio Message'), ('other', 'Other')], default='session', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='main.audiomessage')),
                ('reported_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_safety_reports', to='main.student')),
                ('reported_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_safety_reports', to='main.teacher')),
                ('reported_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_safety_reports', to='main.student')),
                ('reported_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_safety_reports', to='main.teacher')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_safety_reports', to='main.admin')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='main.teachersession')),
            ],
            options={
                'verbose_name_plural': '60c. Safety Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('account_activation', 'Account Activation Consent'), ('live_sessions', 'Live Sessions Consent'), ('messaging', 'Messaging Consent')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='main.studentparentlink')),
            ],
            options={
                'verbose_name_plural': '6c. Parental Consents',
                'unique_together': {('parent_link', 'consent_type')},
            },
        ),
        migrations.CreateModel(
            name='SessionAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('revoked', 'Revoked')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_authorizations', to='main.parentalconsent')),
                ('parent_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_authorizations', to='main.studentparentlink')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_authorizations', to='main.teachersession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_parent_authorizations', to='main.student')),
            ],
            options={
                'verbose_name_plural': '6d. Session Authorizations',
                'unique_together': {('parent_link', 'session')},
            },
        ),
    ]
