# Generated by Django 5.2.5 on 2026-02-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_parentaccount_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersession',
            name='has_minor_participant',
            field=models.BooleanField(default=False, help_text='True if session student is a minor'),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='recording_enabled',
            field=models.BooleanField(default=True, help_text='Enable safety recording/logging for this session'),
        ),
        migrations.AddField(
            model_name='teachersession',
            name='requires_parental_approval',
            field=models.BooleanField(default=False, help_text='Derived from minor participant'),
        ),
        migrations.CreateModel(
            name='SessionParticipantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_role', models.CharField(default='student', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_logs', to='main.teachersession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participant_logs', to='main.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participant_logs', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '60b. Session Participant Logs',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('session', 'Session'), ('audio_message', 'Audio Message'), ('other', 'Other')], default='session', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='main.audiomessage')),
                ('reported_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_safety_reports', to='main.student')),
                ('reported_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_safety_reports', to='main.teacher')),
                ('reported_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_safety_reports', to='main.student')),
                ('reported_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_safety_reports', to='main.teacher')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_safety_reports', to='main.admin')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='main.teachersession')),
            ],
            options={
                'verbose_name_plural': '60c. Safety Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
