# Generated by Django 6.0.2 on 2026-02-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_lessonassignment_description_lessonassignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupannouncement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='groupresource',
            name='link_url',
            field=models.URLField(blank=True, help_text='External link (if no file upload)', null=True),
        ),
        migrations.AlterField(
            model_name='groupresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_resources/'),
        ),
    ]
