# Generated by Django 6.0.2 on 2026-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_groupannouncement_priority_groupresource_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='policy_type',
            field=models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('child_safety', 'Child Safety Policy'), ('code_of_conduct', 'Code of Conduct'), ('background_check_consent', 'Background Check Consent'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacheragreementsignature',
            name='agreement_type',
            field=models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('child_safety', 'Child Safety Policy'), ('code_of_conduct', 'Code of Conduct'), ('background_check_consent', 'Background Check Consent'), ('other', 'Other')], max_length=40),
        ),
    ]
