# Generated by Django 6.0.2 on 2026-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_policydocument_policy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentaccount',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
