# Generated by Django 6.0.2 on 2026-02-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_add_parent_login_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='main.parentaccount'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('message', 'Message Sent'), ('submission', 'Assignment Submission'), ('session_join', 'Session Join'), ('session_leave', 'Session Leave'), ('session_start', 'Session Start'), ('session_end', 'Session End')], max_length=30),
        ),
    ]
