# Generated by Django 6.0.2 on 2026-03-03 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_phase10_audit_logging_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_messages', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '64. Teacher Community Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
