# Generated by Django 6.0.2 on 2026-03-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_teacher_community_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherofficehours',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
