# Generated by Django 6.0.3 on 2026-03-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_add_notes_to_office_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='sender_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin'), ('parent', 'Parent'), ('student', 'Student'), ('school', 'School')], max_length=20),
        ),
    ]
