# Generated by Django 6.0.3 on 2026-03-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_alter_groupmessage_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='main.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='main.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='teacher_student',
            field=models.ForeignKey(blank=True, help_text='The teacher-student assignment this conversation is about (18+ only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='main.teacherstudent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('student', 'Student')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['teacher_student', 'created_at'], name='main_messag_teacher_29425e_idx'),
        ),
    ]
