# Generated by Django 6.0.3 on 2026-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_message_recipient_student_message_sender_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video link for this lesson', max_length=500, null=True),
        ),
    ]
