# Generated by Django 6.0.4 on 2026-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_assignmenttemplate_and_assignmenttemplatequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
