# Generated by Django 6.0.4 on 2026-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_increase_teacher_skills_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
