# Generated by Django 6.0.4 on 2026-05-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_set_teacher_skills_max_length_50'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherverification',
            name='admin_override_for_minors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherverification',
            name='override_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherverification',
            name='override_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_minor_overrides', to='main.admin'),
        ),
        migrations.AddField(
            model_name='teacherverification',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherverification',
            name='override_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherverification',
            name='override_revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_teacher_minor_overrides', to='main.admin'),
        ),
    ]