# Generated by Django 6.0.4 on 2026-05-04 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_stripe_recurring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='admin_conversation_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Stable thread key for admin<->user conversations, e.g. 'admin:1:teacher:3'", max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='main.school'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='main.school'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('student', 'Student'), ('school', 'School')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('student', 'Student'), ('school', 'School')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['admin_conversation_key', 'created_at'], name='main_messag_admin_c_e3e8da_idx'),
        ),
    ]
