# Generated by Django 6.0.5 on 2026-05-30 01:50
# Uses RunSQL with IF NOT EXISTS so it is safe even if the columns already
# exist in the database (e.g. added by a previous manual step).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_modulelesson_teacher_voice_audio'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE main_modulelesson
                    ADD COLUMN IF NOT EXISTS interaction_config jsonb NOT NULL DEFAULT '{}';
                ALTER TABLE main_modulelesson
                    ADD COLUMN IF NOT EXISTS interaction_type varchar(30) NOT NULL DEFAULT 'content';
            """,
            reverse_sql="""
                ALTER TABLE main_modulelesson DROP COLUMN IF EXISTS interaction_config;
                ALTER TABLE main_modulelesson DROP COLUMN IF EXISTS interaction_type;
            """,
        ),
        # Keep Django's state in sync with the schema we just ensured exists.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='modulelesson',
                    name='interaction_config',
                    field=models.JSONField(default=dict),
                ),
                migrations.AddField(
                    model_name='modulelesson',
                    name='interaction_type',
                    field=models.CharField(default='content', max_length=30),
                ),
            ],
            database_operations=[],   # DDL already handled above
        ),
    ]
