# Generated by Django 6.0.5 on 2026-05-31 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_lessonblock_practice_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Block-type-specific configuration (captions, questions, timer duration, etc.)'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text="e.g. '6-Month Guitar Journey'", max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_months', models.PositiveIntegerField(default=6)),
                ('is_active', models.BooleanField(default=False, help_text='Published and visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_paths', to='main.admin')),
                ('created_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_paths', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '73. Learning Paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField(default=1, help_text='Which month of the path this course belongs to (1 = first)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position within the path (0 = first)')),
                ('title_override', models.CharField(blank=True, default='', help_text='Optional display name for this course in the path context', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_learning_paths', to='main.course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='main.learningpath')),
            ],
            options={
                'verbose_name_plural': '74. Learning Path Courses',
                'ordering': ['order', 'id'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_course_index', models.PositiveIntegerField(default=0, help_text='Zero-based index into path_courses order — which course the student is currently on')),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.learningpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to='main.student')),
            ],
            options={
                'verbose_name_plural': '75. Learning Path Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'learning_path')},
            },
        ),
    ]
